baseURL = "https://www.lukasrieder.com/"
languageCode = "en"
title = "Lukas Rieder"
theme = "whiteplain"
copyright = "Copyright 2018, Lukas Rieder"

[params.author]
  name = "Lukas Rieder"
  gravatar = "171de85d4d79cb7afe725174fb099137"
  github = "Overbryd"
  stackoverflow = "Overbryd"
  slideshare = "Overbryd"

